### ISSUE TITLE
Issue with regex negative lookahead

### ISSUE THREAD

**Issue by goatandsheep** [c9/c9.ide.find#1]
My negative lookahead regex is not working properly. When I try to find `.(?!_)BED` in a file, `_BED` still comes up. When I tested it on other regex sites, such as [debuggex](https://www.debuggex.com), the negative lookahead worked fine.

**Comment by nightwing** [comment]
`/.(?!_)BED/.exec("_BED")` returns a match, because the first dot matches `_`, which is not followed by `_`, so the rest can match.
maybe you are looking for `[^_]BED`?

**Comment by goatandsheep** [comment]
yup that works. sorry about this!
